image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
    - hugo
    - apt -y update && apt -y install imagemagick
    - bash scripts/generate-allreads.sh
    - bash scripts/generate-bookshelf.sh
    - bash scripts/generate-star-quotes.sh
    - ln -s content/posts/star-quotes.md static/star-quotes.md
    #- cd static/do-you-know-this-person-243987978423987fsdalksadflqrweoyzv/
    #- bash update_photo_array.sh
    #- cd -
    - hugo
    - ls public/star-quotes

  artifacts:
    paths:
    - public
    expire_in: 1 week
  only:
  - master
  interruptible: true
