image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo
  - bash scripts/generate-allbooks.sh

  artifacts:
    paths:
    - public
    expire_in: 1 week
  only:
  - master
  interruptible: true
