image: klakegg/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo
  - cd random-thoughts && hugo && cd -
  - mv random-thoughts/public public/random-thoughts # This command is artistic
  - cd public && rm index.xml && ln -s posts/index.xml

  artifacts:
    paths:
    - public
    expire_in: 1 week
  only:
  - master
  interruptible: true
