image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo
  - cd random-thoughts && hugo && cd -
  - mv random-thoughts/public public/random-thoughts # This command is artistic

  artifacts:
    paths:
    - public
  only:
  - master
