image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - sudo apt -y install imagemagick
  - bash scripts/generate-allreads.sh
  - cd static/do-you-know-this-person-243987978423987fsdalksadflqrweoyzv/
  - bash update_photo_array.sh
  - cd -
  - hugo

  artifacts:
    paths:
    - public
    expire_in: 1 week
  only:
  - master
  interruptible: true
