image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo
  - cd public && rm index.xml && ln -s posts/index.xml

  artifacts:
    paths:
    - public
    expire_in: 1 week
  only:
  - master
  interruptible: true
